### PR TITLE
Adding FMIL to .gitignore since it's checked out in the source directory

### PR DESCRIPTION
**Pull request by otronarp**
Since the CMake project checks out FMIL in the source directory it's reasonable to provide a default .gitignore that ignores the FMIL directory,

### CODE REVIEW

**Comment by sjoelund** [comment]
More reasonable would perhaps be using git submodule or git subtree. But if you want to keep CMake pulling git repositories instead of using git primitives, a git ignore seems reasonable

**Comment by otronarp** [comment]
Sure, but FMIL lives in svn and I'm not sure that you can use svn repositories as submodules?

**Comment by tbeu** [comment]
FMIL also lives as GitHub mirror, see https://github.com/svn2github/FMILibrary.

**Comment by otronarp** [comment]
Which is an unofficial poll based mirror and besides that it doesn't mirror tags and the compliance checker is tied to a specific FMIL release tag. If jmodeliga.org would release tar balls one could point to that instead, but they are using zip files (http://www.jmodelica.org/FMILibrary) and as far as I know CMake external projects cannot handle zip files.

**Comment by sjoelund** [comment]
git subtree is not tied to any specific git repository though.

**Pull request merged**
