### PR TITLE
Update CMakeLists.txt

### LINKED ISSUE #52: Invalid link to FMILibrary repository
The link 
SVN_REPOSITORY "https://svn.jmodelica.org/FMILibrary/tags/2.0.3"
is invalid. The FMI library has moved to
https://github.com/svn2github/FMILibrary

### PR DESCRIPTION
**Pull request by griffin-modelon**
Updated to point to current location of FMIL.
Fixes #52

### CODE REVIEW

**Comment by hubertus65** [comment]
This PR fixes issue 52, https://github.com/modelica-tools/FMUComplianceChecker/issues/52. I am unsure who "owns" this repository and should merge this pull request. Any comments?

**Comment by beutlich** [comment]
I believe maintenance is not clarified, which is the reason of the stopped development and maintenance. I hope someone from @modelon-community can volunteer here, maybe based on budget plan of MAP-FMI.

**Comment by chrbertsch** [comment]
> I am unsure who "owns" this repository and should merge this pull request. 
... 
> I believe maintenance is not clarified

Who has write access to this repository? Who can grant write access? Who is the admin of "modelica" tools? For such a small maintenance fix we should should find a simple solution.

@andreas-junghanns, @t-sommer: we shall clarify the future role and maintenance of the FMU compliance checker.

**Comment by beutlich** [comment]
> Who has write access to this repository?

@efredriksson-modelon and @victorjoh have write access.

> Who can grant write access?

Admins can do.

> Who is the admin of "modelica-tools"?

@dietmarw @mtiller @raphaelchenouard @adeas31 @svenruetz and me have admin rights.

> For such a small maintenance fix we should should find a simple solution.

Merging now...

**Pull request merged**
